name: End-to-end tests
on: [push]
jobs:
   cypress-run:
      runs-on: 
       steps:
        - name: Checkout
          uses: actions/checkout@v2
         # Install NPM dependecies, cache them correctly
         # and run all Cypress testes
        - name: Cypress run
          uses: cypress-io/github-actions@v2  